-- MySQL Script generated by MySQL Workbench
-- Mon May  6 17:48:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `main`.`restaurant` (
  `PK_idRestaurant` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_idRestaurant`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`event` ;

CREATE TABLE IF NOT EXISTS `main`.`event` (
  `PK_idEvent` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `beginningDate` DATE NOT NULL,
  `endingDate` DATE NOT NULL,
  `FK_restaurant` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`PK_idEvent`),
  INDEX `fk_restaurant_event_idx` (`FK_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_event`
    FOREIGN KEY (`FK_restaurant`)
    REFERENCES `main`.`restaurant` (`PK_idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`sensortype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`sensortype` ;

CREATE TABLE IF NOT EXISTS `main`.`sensortype` (
  `PK_idSensorType` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`PK_idSensorType`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`sensor` ;

CREATE TABLE IF NOT EXISTS `main`.`sensor` (
  `PK_idSensor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `position` INT(10) UNSIGNED NOT NULL,
  `FK_restaurant` INT(10) UNSIGNED NOT NULL,
  `FK_sensorType` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`PK_idSensor`),
  INDEX `FK_sensorRestaurant_idx` (`FK_restaurant` ASC) VISIBLE,
  INDEX `FK_sensorType_idx` (`FK_sensorType` ASC) VISIBLE,
  CONSTRAINT `FK_restaurant_sensor`
    FOREIGN KEY (`FK_restaurant`)
    REFERENCES `main`.`restaurant` (`PK_idRestaurant`)
    ON UPDATE CASCADE,
  CONSTRAINT `FK_sensorType`
    FOREIGN KEY (`FK_sensorType`)
    REFERENCES `main`.`sensortype` (`PK_idSensorType`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`measure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`measure` ;

CREATE TABLE IF NOT EXISTS `main`.`measure` (
  `PK_idMeasure` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `measure` DECIMAL(10,0) NOT NULL,
  `FK_sensor` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`PK_idMeasure`),
  INDEX `fk_Sensor_idx` (`FK_sensor` ASC) VISIBLE,
  CONSTRAINT `fk_Sensor`
    FOREIGN KEY (`FK_sensor`)
    REFERENCES `main`.`sensor` (`PK_idSensor`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`restaurantavailabilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`restaurantavailabilities` ;

CREATE TABLE IF NOT EXISTS `main`.`restaurantavailabilities` (
  `PK_idRestaurantAvailabilities` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `openingTime` TIME NOT NULL,
  `closingTime` TIME NOT NULL,
  `FK_restaurant` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`PK_idRestaurantAvailabilities`),
  INDEX `fk_Restaurant_idx` (`FK_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurant_Availability`
    FOREIGN KEY (`FK_restaurant`)
    REFERENCES `main`.`restaurant` (`PK_idRestaurant`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `main`.`waitingtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main`.`waitingtime` ;

CREATE TABLE IF NOT EXISTS `main`.`waitingtime` (
  `PK_idWaitingTime` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `waitingTime` INT(10) UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `FK_restaurant` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`PK_idWaitingTime`),
  INDEX `FK_restaurant_idx` (`FK_restaurant` ASC) VISIBLE,
  CONSTRAINT `FK_restaurant_waitingTime`
    FOREIGN KEY (`FK_restaurant`)
    REFERENCES `main`.`restaurant` (`PK_idRestaurant`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
